apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-api
  namespace: demo1
  labels:
    app: orders-api
    app.kubernetes.io/part-of: aiops-incident-lab
spec:
  replicas: 4
  selector:
    matchLabels:
      app: orders-api
  template:
    metadata:
      labels:
        app: orders-api
        app.kubernetes.io/name: orders-api
    spec:
      containers:
        - name: orders-api
          image: aiops-orders-api:v3
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: OTEL_SERVICE_NAME
              value: orders-api
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: otel-collector.tracing.svc.cluster.local:4317
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: orders-api
  namespace: demo1
  labels:
    app: orders-api
    app.kubernetes.io/part-of: aiops-incident-lab
spec:
  selector:
    app: orders-api
  ports:
    - name: http
      port: 80
      targetPort: http
