apiVersion: v1
kind: Service
metadata:
  name: nginx-demo1-svc
  namespace: demo1
  labels:
    app.kubernetes.io/name: nginx-demo1
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: nginx-demo1
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http

