apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-datasource
  namespace: monitoring
  labels:
    grafana_datasource: "1"
    app.kubernetes.io/part-of: aiops-incident-lab
data:
  tempo-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Tempo
        uid: tempo
        type: tempo
        access: proxy
        url: http://tempo.tracing.svc.cluster.local:3200
        editable: false
        jsonData:
          httpMethod: GET
