apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-datasource
  namespace: monitoring
  labels:
    grafana_datasource: "1"
    app.kubernetes.io/part-of: aiops-incident-lab
data:
  loki-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Loki
        uid: loki
        type: loki
        access: proxy
        url: http://loki.logs.svc.cluster.local:3100
        editable: false
        jsonData:
          derivedFields:
            - name: TraceID
              matcherRegex: "trace_id=([a-f0-9]{32})"
              datasourceUid: tempo
              url: "${__value.raw}"
              urlDisplayLabel: View trace
